# Generated by Django 3.2.7 on 2021-10-19 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('url_img', models.URLField(max_length=255)),
                ('id_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.destination')),
            ],
        ),
    ]
